application/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['as' => '/', 'uses' => 'PagesController@showHome']);
Route::get('register', ['as' => 'register', 'uses' => 'UsersController@getRegister']);
Route::post('register', ['as' => 'register', 'uses' => 'UsersController@postRegister']);
Route::get('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@getTerms']);
Route::post('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@postTerms']);
Route::get('activate-account/{activationCode}', ['as' => 'activate_account', 'uses' => 'UsersController@activate']);


Route::get('login', ['as' => 'login', 'uses' => 'UsersController@getLogin']);
Route::post('login', ['as' => 'login', 'uses' => 'UsersController@postLogin']);
Route::get('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@getRestorePasswordRequest']);
Route::post('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@postRestorePasswordRequest']);
Route::post('reset-password', ['as' => 'reset_password', 'uses' => 'UsersController@postResetPassword']);
Route::get('reset-password/{code}', ['as' => 'reset_password', 'uses' => 'UsersController@getResetPassword']);

Route::group(array('before' => 'auth'), function()
{
    Route::get('logout', ['as' => 'logout', 'uses' => 'UsersController@getLogout']);

    Route::get('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@getSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);

    Route::group(array('before' => 'user'), function() {
        Route::get('search', ['as' => 'books_search', 'uses' => 'BooksController@search']);
		Route::get('latest', ['as' => 'latest_books', 'uses' => 'BooksController@latest']);
		Route::get('my-rents', ['as' => 'user_rents', 'uses' => 'RentsController@userIndex']);
		Route::get('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@create']);
		Route::post('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@store']);
    });

    Route::group(array('before' => 'admin'), function() {
		Route::resource('books', 'BooksController');
		Route::resource('penalties', 'PenaltiesController');
		Route::resource('discounts', 'DiscountsController');
		Route::resource('payments', 'PaymentsController');
		Route::resource('rents', 'RentsController');
        Route::resource('users', 'UsersController');

		Route::post('end-rent', ['as' => 'end_rent', 'uses' => 'RentsController@end']);
    });
});

application/app/models/Penalty.php
<?php

class Penalty extends BaseModel {
	public $fillable = ['user_id', 'amount'];

	public function user()
	{
		return $this->belongsTo('User');
	}
}

application/app/controllers/PenaltiesController.php
<?php

class PenaltiesController extends BaseController {
	/**
	* Book Repository
	*
	* @var Book
	*/
	protected $penalty;

	public function __construct(Penalty $penalty)
	{
		$this->penalty = $penalty;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$penalties = Penalty::orderBy('created_at', 'desc')->paginate($this->paginationLimit);
        return View::make('penalties.index', compact('penalties'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
        $users = $this->getUsersList();

        return View::make('penalties.create', compact('users'));
	}
	
	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Penalty::$rules);

		if ($validation->passes())
		{
			$p = $this->penalty->create($input);

			$this->flashSuccess(sprintf('Kara %d PLN została przydzielona', $input['amount']));

			return Redirect::route('penalties.show', $p->id);
		}

		return Redirect::route('penalites.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'Formularz zawiera błędy.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$penalty = $this->penalty->findOrFail($id);

		return View::make('penalties.show', compact('penalty'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$penalty = $this->penalty->find($id);

		if (is_null($penalty))
		{
			return Redirect::route('penalties.index');
		}

		$users = $this->getUsersList();

		return View::make('penalties.edit', compact('penalty', 'users'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Penalty::$rules);

		if ($validation->passes())
		{
			$penalty = $this->penalty->find($id);
			$penalty->update($input);

			return Redirect::route('penalties.show', $id);
		}

		return Redirect::route('penalties.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'Formularz zawiera błędy.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->penalty->find($id)->delete();

		$this->flashSuccess('Usunięto');

		return Redirect::route('penalties.index');
	}

}

application/app/views/penalties/create.blade.php
@extends('layouts.user', ['current' => 'penalties.index'])

<?php
$items = [
	'penalties.index' => 'Lista',
	'penalties.create' => 'Dodaj',
];
?>

@include('partials.mid_menu_list', ['items' => $items, 'current' => 'penalties.create'])

@section('content2')

     {{ Former::open()->route('penalties.store') }}

	@include('forms.penalty')

@stop

@include('packages.select')

application/app/views/penalties/edit.blade.php
@extends('layouts.user', ['current' => 'alerts.index'])

<?php
$items = [
    'penalties.index' => 'Lista',
    'penalties.create' => 'Dodaj',
    ['penalties.edit', 'Edycja', [$penalty->id]],
    ['penalties.show', 'Podgląd', [$penalty->id]],
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'penalties.edit'])


@section('content2')

	{{ Former::open()->route('penalties.update', [$penalty->id])->populate($penalty) }}

	@include('forms.penalty')

@stop

@include('packages.select')

application/app/views/penalties/index.blade.php
@extends('layouts.user', ['current' => 'penalties.index'])

<?php
$items = [
    'penalties.index' => 'Lista',
    'penalties.create' => 'Dodaj'
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'penalties.index'])

@section('content2')

    @if ($penalties->count())
        <div class="table-responsive">
            <table class="table table-blue mt2em">
                <thead>
                <tr>
                <th>Użytkownik</th>
		<th>Wartość kary</th>
		<th>Utworzono</th>
		<th>Ostatnia modyfikacja</th>
		<th>Akcja</th>
                </tr>
            </thead>

                <tbody>
                    @foreach ($penalties as $penalty)
                        <tr>
                            <td>{{{ $penalty->user->name() }}}</td>
                            <td>{{{ $penalty->amount }}} PLN</td>
                            <td>{{{ $penalty->created_at->addDays($penalty->days)->format('d/m/Y') }}}</td>
                            <td>{{{ $penalty->updated_at->addDays($penalty->days)->format('d/m/Y') }}}</td>
                            <td class="text-right  col-sm-2">
                                {{ link_to_route('penalties.show', 'Podląd', array($penalty->id), array('class' => 'btn btn-info')) }}
                                {{ link_to_route('penalties.edit', 'Edycja', array($penalty->id), array('class' => 'btn btn-warning')) }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @include('partials.pagination', ['object' => $penalties])
    @else
        @nothingFound('Nie ma żadnych kar!')
    @endif

@stop

application/app/views/penalties/show.blade.php
@extends('layouts.user', ['current' => 'penalties.index'])

<?php
$items = [
    'penalties.index' => 'Lista',
    'penalties.create' => 'Dodaj',
    ['penalties.edit', 'Edycja', [$penalty->id]],
    ['penalties.show', 'Podgląd', [$penalty->id]],
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'penalties.show'])

@section('content2')

    <div class="table-responsive">
        <table class="table table-blue mt2em">
            <thead>
                <tr>
		<th>Wartość kary</th>
		<th>Utworzono</th>
		<th>Ostatnia modyfikacja</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>{{{ $penalty->amount }}} PLN</td>
            	    <td>{{{ $penalty->created_at->addDays($penalty->days)->format('d/m/Y') }}}</td>
                    <td>{{{ $penalty->updated_at->addDays($penalty->days)->format('d/m/Y') }}}</td>
                </tr>
            </tbody>
        </table>
    </div>

    {{ Form::open(array('class' => 'mt2em', 'method' => 'DELETE', 'route' => array('penalties.destroy', $penalty->id))) }}
    {{ Form::submit('Usuń karę', array('class' => 'btn btn-danger remove-submit')) }}
    {{ Form::close() }}
@stop

@include("packages.bootbox")