application/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['as' => '/', 'uses' => 'PagesController@showHome']);
Route::get('register', ['as' => 'register', 'uses' => 'UsersController@getRegister']);
Route::post('register', ['as' => 'register', 'uses' => 'UsersController@postRegister']);
Route::get('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@getTerms']);
Route::post('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@postTerms']);
Route::get('activate-account/{activationCode}', ['as' => 'activate_account', 'uses' => 'UsersController@activate']);


Route::get('login', ['as' => 'login', 'uses' => 'UsersController@getLogin']);
Route::post('login', ['as' => 'login', 'uses' => 'UsersController@postLogin']);
Route::get('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@getRestorePasswordRequest']);
Route::post('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@postRestorePasswordRequest']);
Route::post('reset-password', ['as' => 'reset_password', 'uses' => 'UsersController@postResetPassword']);
Route::get('reset-password/{code}', ['as' => 'reset_password', 'uses' => 'UsersController@getResetPassword']);

Route::group(array('before' => 'auth'), function()
{
    Route::get('logout', ['as' => 'logout', 'uses' => 'UsersController@getLogout']);

    Route::get('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@getSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);

    Route::group(array('before' => 'user'), function() {
        Route::get('search', ['as' => 'books_search', 'uses' => 'BooksController@search']);
		Route::get('latest', ['as' => 'latest_books', 'uses' => 'BooksController@latest']);
		Route::get('my-rents', ['as' => 'user_rents', 'uses' => 'RentsController@userIndex']);
		Route::get('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@create']);
		Route::post('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@store']);
    });

    Route::group(array('before' => 'admin'), function() {
		Route::resource('books', 'BooksController');
		Route::resource('penalties', 'PenaltiesController');
		Route::resource('discounts', 'DiscountsController');
		Route::resource('payments', 'PaymentsController');
		Route::resource('rents', 'RentsController');
        Route::resource('users', 'UsersController');

		Route::post('end-rent', ['as' => 'end_rent', 'uses' => 'RentsController@end']);
    });
});

application/app/models/Payment.php
<?php

class Payment extends BaseModel {

	public $fillable = ['user_id', 'amount'];

	public function user()
	{
		return $this->belongsTo('User');
	}
}

application/app/controllers/PaymentsController.php
<?php

class PaymentsController extends BaseController {

	/**
	 * Book Repository
	 *
	 * @var Book
	 */
	protected $payment;

	public function __construct(Payment $payment)
	{
		$this->payment = $payment;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$payments = Payment::orderBy('created_at', 'desc')->paginate($this->paginationLimit);
        return View::make('payments.index', compact('payments'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$users = $this->getUsersList();

        return View::make('payments.create', compact('users'));

	}
	
	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Payment::$rules);

		if ($validation->passes())
		{
			$p = $this->payment->create($input);
			$this->flashSuccess('Płatność została zapisana');

			return Redirect::route('payments.show', $p->id);
		}

		return Redirect::route('payments.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'Formularz zawiera błędy.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$payment = $this->payment->findOrFail($id);

		return View::make('payments.show', compact('payment'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$payment = $this->payment->find($id);

		if (is_null($payment))
		{
			return Redirect::route('payments.index');
		}
                $users = User::lists(DB::raw('CONCAT(first_name, " ", last_name)'), 'id');

		return View::make('payments.edit', compact('payment', 'users'));

		$users = $this->getUsersList();

		return View::make('payments.edit', compact('payment', 'users'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Payment::$rules);

		if ($validation->passes())
		{
			$payment = $this->payment->find($id);
			$payment->update($input);

			return Redirect::route('payments.show', $id);
		}

		return Redirect::route('payments.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'Formularz zawiera błędy.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->payment->find($id)->delete();

		$this->flashSuccess('Usunięto');

		return Redirect::route('payments.index');
	}

}

application/app/views/payments/create.blade.php
@extends('layouts.user', ['current' => 'payments.index'])

<?php
$items = [
	'payments.index' => 'Lista',
	'payments.create' => 'Dodaj',
];
?>

@include('partials.mid_menu_list', ['items' => $items, 'current' => 'payments.create'])

@section('content2')

    {{ Former::open()->route('payments.store') }}

	@include('forms.payment')

@stop

@include('packages.select')

application/app/views/payments/edit.blade.php
@extends('layouts.user', ['current' => 'payments.index'])

<?php
$items = [
    'payments.index' => 'Lista',
    'payments.create' => 'Dodaj',
    ['payments.edit', 'Edycja', [$payment->id]],
    ['payments.show', 'Podgląd', [$payment->id]],
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'payments.edit'])

@section('content2')

	{{ Former::open()->route('payments.update', [$payment->id])->populate($payment) }}

	@include('forms.payment')

@stop

@include('packages.select')

application/app/views/payments/index.blade.php
@extends('layouts.user', ['current' => 'payments.index'])

<?php
$items = [
    'payments.index' => 'Lista',
    'payments.create' => 'Dodaj'
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'payments.index'])

@section('content2')

    @if ($payments->count())
        <div class="table-responsive">
            <table class="table table-blue mt2em">
                <thead>
                <tr>
                <th>Użytkownik</th>
		<th>Wartość płatności</th>
		<th>Utworzono</th>
		<th>Ostatnia modyfikacja</th>
		<th>Akcja</th>
                </tr>
            </thead>

                <tbody>
                    @foreach ($payments as $payment)
                        <tr>
                            <td>{{{ $payment->user->name() }}}</td>
                            <td>{{{ $payment->amount }}} PLN</td>
                            <td>{{{ $payment->created_at->addDays($payment->days)->format('d/m/Y') }}}</td>
                            <td>{{{ $payment->updated_at->addDays($payment->days)->format('d/m/Y') }}}</td>
                            <td class="text-right  col-sm-2">
                                {{ link_to_route('payments.show', 'Podląd', array($payment->id), array('class' => 'btn btn-info')) }}
                                {{ link_to_route('payments.edit', 'Edycja', array($payment->id), array('class' => 'btn btn-warning')) }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @include('partials.pagination', ['object' => $payments])
    @else
        @nothingFound('Nie ma żadnych płatności!')
    @endif

@stop

application/app/views/payments/show.blade.php
@extends('layouts.user', ['current' => 'payments.index'])

<?php
$items = [
    'payments.index' => 'Lista',
    'payments.create' => 'Dodaj',
    ['payments.edit', 'Edycja', [$payment->id]],
    ['payments.show', 'Podgląd', [$payment->id]],
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'payments.show'])

@section('content2')

    <div class="table-responsive">
        <table class="table table-blue mt2em">
            <thead>
                <tr>
                <th>Użytkownik</th>
		<th>Wartość wpłaty</th>
		<th>Utworzono</th>
		<th>Ostatnia modyfikacja</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>{{{ $payment->user->name() }}}</td>
                    <td>{{{ $payment->amount }}} PLN</td>
            	    <td>{{{ $payment->created_at->addDays($payment->days)->format('d/m/Y') }}}</td>
                    <td>{{{ $payment->updated_at->addDays($payment->days)->format('d/m/Y') }}}</td>
                </tr>
            </tbody>
        </table>
    </div>

    {{ Form::open(array('class' => 'mt2em', 'method' => 'DELETE', 'route' => array('payments.destroy', $payment->id))) }}
    {{ Form::submit('Usuń płatność', array('class' => 'btn btn-danger remove-submit')) }}
    {{ Form::close() }}
@stop

@include("packages.bootbox")