application/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['as' => '/', 'uses' => 'PagesController@showHome']);
Route::get('register', ['as' => 'register', 'uses' => 'UsersController@getRegister']);
Route::post('register', ['as' => 'register', 'uses' => 'UsersController@postRegister']);
Route::get('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@getTerms']);
Route::post('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@postTerms']);
Route::get('activate-account/{activationCode}', ['as' => 'activate_account', 'uses' => 'UsersController@activate']);


Route::get('login', ['as' => 'login', 'uses' => 'UsersController@getLogin']);
Route::post('login', ['as' => 'login', 'uses' => 'UsersController@postLogin']);
Route::get('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@getRestorePasswordRequest']);
Route::post('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@postRestorePasswordRequest']);
Route::post('reset-password', ['as' => 'reset_password', 'uses' => 'UsersController@postResetPassword']);
Route::get('reset-password/{code}', ['as' => 'reset_password', 'uses' => 'UsersController@getResetPassword']);

Route::group(array('before' => 'auth'), function()
{
    Route::get('logout', ['as' => 'logout', 'uses' => 'UsersController@getLogout']);

    Route::get('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@getSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);

    Route::group(array('before' => 'user'), function() {
        Route::get('search', ['as' => 'books_search', 'uses' => 'BooksController@search']);
		Route::get('latest', ['as' => 'latest_books', 'uses' => 'BooksController@latest']);
		Route::get('my-rents', ['as' => 'user_rents', 'uses' => 'RentsController@userIndex']);
		Route::get('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@create']);
		Route::post('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@store']);
    });

    Route::group(array('before' => 'admin'), function() {
		Route::resource('books', 'BooksController');
		Route::resource('penalties', 'PenaltiesController');
		Route::resource('discounts', 'DiscountsController');
		Route::resource('payments', 'PaymentsController');
		Route::resource('rents', 'RentsController');
        Route::resource('users', 'UsersController');

		Route::post('end-rent', ['as' => 'end_rent', 'uses' => 'RentsController@end']);
    });
});

application/app/models/Book.php
<?php

class Book extends Eloquent
{
	protected $guarded = array();

	public static $rules = [
		'title' => 'required',
		'description' => 'required',
		'isbn' => 'required',
		'author' => 'required',
	];

}

application/app/controllers/BooksController.php
<?php

class BooksController extends BaseController
{
	/**
	 * Book Repository
	 *
	 * @var Book
	 */
	protected $book;

	public function __construct(Book $book)
	{
		$this->book = $book;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$books = Book::paginate($this->paginationLimit);
		return View::make('books.index', compact('books'));
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function latest()
	{
		$books = Book::orderBy('created_at', 'desc')->where('created_at', '>=', date('Y-m-d', strtotime('2 days ago')))->paginate($this->paginationLimit);
		$current = 'latest_books';
		return View::make('books.user_index', compact('books', 'current'));
	}

	public function search()
	{
		$input = Input::all();

		$q = Book::orderBy('created_at', 'desc');

		foreach(['title', 'description'] as $field)
		{
			if(array_key_exists($field, $input))
			{
				$q->where(DB::raw("LOWER({$field})"), 'LIKE', "%" . strtolower($input[$field]) . "%");
			}
		}

		$books =$q->paginate($this->paginationLimit);

		$current = 'books_search';

		return View::make('books.user_index', compact('books', 'current'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('books.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Book::$rules);

		if ($validation->passes())
		{
			$p=$this->book->create($input);

			return Redirect::route('books.show', $p->id);
		}

		return Redirect::route('books.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'Formularz zawiera błędy.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function show($id)
	{
		$book = $this->book->findOrFail($id);

		return View::make('books.show', compact('book'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function edit($id)
	{
		$book = $this->book->find($id);

		if (is_null($book))
		{
			return Redirect::route('books.index');
		}

		return View::make('books.edit', compact('book'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Book::$rules);

		if ($validation->passes())
		{
			$book = $this->book->find($id);
			$book->update($input);

			return Redirect::route('books.show', $id);
		}

		return Redirect::route('books.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'Formularz zawiera błędy.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int $id
	 *
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->book->find($id)->delete();

		$this->flashSuccess('Książka została usunięta');

		return Redirect::route('books.index');
	}

}

application/app/views/books/create.blade.php
@extends('layouts.user', ['current' => 'books.index'])

<?php
$items = [
	'books.index' => 'Lista',
	'books.create' => 'Dodaj książkę',
];
?>

@include('partials.mid_menu_list', ['items' => $items, 'current' => 'books.create'])

@section('content2')

	{{ Former::open()->route('books.store') }}

	@include('forms.book')

@stop

application/app/views/books/edit.blade.php
@extends('layouts.user', ['current' => 'books.index'])

<?php
$items = [
	'books.index' => 'Lista',
	'books.create' => 'Dodaj książkę',
	['books.edit', 'Edycja', [$book->id]],
	['books.show', 'Podgląd', [$book->id]],
];
?>

@include('partials.mid_menu_list', ['items' => $items, 'current' => 'books.edit'])

@section('content2')

	{{ Former::open()->route('books.update', $book->id)->populate($book) }}

	@include('forms.book')

@stop

application/app/views/books/index.blade.php
@extends('layouts.user', ['current' => 'books.index'])

<?php
$items = [
    'books.index' => 'Lista',
    'books.create' => 'Dodaj książkę'
];
?>

@include('partials.mid_menu_list', ['items' => $items, 'current' => 'books.index'])

@section('content2')

    @if ($books->count())
        <div class="table-responsive">
            <table class="table table-blue">
                <thead>
                    <tr>
                        <th class="col-sm-3">Tytuł</th>
                        <th class="col-sm-2">ISBN</th>
                        <th>Autor</th>
                        <th>Rok</th>
                        <th class="text-right col-sm-3">Menu</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($books as $book)
                        <tr>
                            <td>{{{ $book->title }}}</td>
							<td>{{{ $book->isbn }}}</td>
							<td>{{{ $book->author }}}</td>
							<td>{{{ $book->year }}}</td>
							<td class="text-right  col-sm-4">
								{{ link_to_route('books.show', 'Podgląd', array($book->id), array('class' => 'btn btn-info')) }}
								{{ link_to_route('books.edit', 'Edycja', array($book->id), array('class' => 'btn btn-warning')) }}

								{{ Former::open()->class('form-inline')->route('books.destroy', $book->id) }}
								{{ Form::submit('Usuń', array('class' => 'btn btn-danger remove-submit')) }}
								{{ Form::close() }}
							</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @include('partials.pagination', ['object' => $books])
    @else
        @nothingFound('Nie dodano żadnych książek')
    @endif

@stop

@include('packages.bootbox')

application/app/views/books/show.blade.php
@extends('layouts.user', ['current' => 'books.index'])

<?php
$items = [
    'books.index' => 'Lista',
    'books.create' => 'Dodaj książkę',
    ['books.edit', 'Edycja', [$book->id]],
    ['books.show', 'Podgląd', [$book->id]],
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'books.show'])

@section('content2')

	<dl class="ul-horizontal">
		<dt>Tytuł</dt> <td>{{{ $book->title }}}</td>
		<dt>Opis</dt> <td>{{{ $book->description }}}</td>
		<dt>Isbn</dt> <td>{{{ $book->isbn }}}</td>
		<dt>Autor</dt> <td>{{{ $book->author }}}</td>
		<dt>Rok</dt> <td>{{{ $book->year }}}</td>

	</dl>

    {{ Form::open(array('class' => 'mt2em mb2em', 'method' => 'DELETE', 'route' => array('books.destroy', $book->id))) }}
    {{ Form::submit('Usuń książkę', array('class' => 'btn btn-danger remove-submit')) }}
    {{ Form::close() }}
@stop

@include("packages.bootbox")

application/app/views/books/user_index.blade.php
@extends('layouts.user', ['current' => $current])

@section('content2')

	@if($current == 'books_search')
		{{ Former::open()->method('get') }}
		{{ Former::text('title', 'Tytuł') }}
		{{ Former::text('description', 'Opis') }}
		{{ Former::actions()->large_primary_submit('Wyślij') }}
		{{ Former::close() }}
	@endif

    @if ($books->count())
        <div class="table-responsive">
            <table class="table table-blue">
                <thead>
                    <tr>
                        <th class="col-sm-3">Tytuł</th>
                        <th class="col-sm-2">Autor</th>
                        <th>Opis</th>
                        <th>Dodano</th>
                        <th class="text-right">Menu</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($books as $book)
                        <tr>
                            <td>{{{ $book->title }}}</td>
							<td>{{{ $book->author }}}</td>
							<td>{{{ $book->description }}}</td>
							<td>{{{ $book->created_at->format('d/m/Y') }}}</td>
							<td class="text-right col-sm-3">
								{{ HTML::linkRoute('new_rent', 'Wypożycz', $book->id, ['class' => 'btn btn-success']) }}
							</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @include('partials.pagination', ['object' => $books])
    @else
        @nothingFound('Brak książek do wyświetlenia')
    @endif

@stop