application/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', ['as' => '/', 'uses' => 'PagesController@showHome']);
Route::get('register', ['as' => 'register', 'uses' => 'UsersController@getRegister']);
Route::post('register', ['as' => 'register', 'uses' => 'UsersController@postRegister']);
Route::get('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@getTerms']);
Route::post('accept-terms', ['as' => 'accept_terms', 'uses' => 'UsersController@postTerms']);
Route::get('activate-account/{activationCode}', ['as' => 'activate_account', 'uses' => 'UsersController@activate']);


Route::get('login', ['as' => 'login', 'uses' => 'UsersController@getLogin']);
Route::post('login', ['as' => 'login', 'uses' => 'UsersController@postLogin']);
Route::get('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@getRestorePasswordRequest']);
Route::post('password-restore-request', ['as' => 'password_restore_request', 'uses' => 'UsersController@postRestorePasswordRequest']);
Route::post('reset-password', ['as' => 'reset_password', 'uses' => 'UsersController@postResetPassword']);
Route::get('reset-password/{code}', ['as' => 'reset_password', 'uses' => 'UsersController@getResetPassword']);

Route::group(array('before' => 'auth'), function()
{
    Route::get('logout', ['as' => 'logout', 'uses' => 'UsersController@getLogout']);

    Route::get('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@getSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);
    Route::post('ustawienia-konta', ['as' => 'settings', 'uses' => 'UsersController@postSettings']);

    Route::group(array('before' => 'user'), function() {
        Route::get('search', ['as' => 'books_search', 'uses' => 'BooksController@search']);
		Route::get('latest', ['as' => 'latest_books', 'uses' => 'BooksController@latest']);
		Route::get('my-rents', ['as' => 'user_rents', 'uses' => 'RentsController@userIndex']);
		Route::get('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@create']);
		Route::post('new-rent/{bookId}', ['as' => 'new_rent', 'uses' => 'RentsController@store']);
    });

    Route::group(array('before' => 'admin'), function() {
		Route::resource('books', 'BooksController');
		Route::resource('penalties', 'PenaltiesController');
		Route::resource('discounts', 'DiscountsController');
		Route::resource('payments', 'PaymentsController');
		Route::resource('rents', 'RentsController');
        Route::resource('users', 'UsersController');

		Route::post('end-rent', ['as' => 'end_rent', 'uses' => 'RentsController@end']);
    });
});

application/app/models/User.php
<?php

use Hampel\Sentry\Auth\SentryUser;

/**
 * Class User
 */
class User extends SentryUser {

    /**
     * Fields fillable on bulk save.
     *
     * @var array
     */
    protected  $fillable = ['first_name', 'last_name', 'email', 'password'];

    /**
     * Use soft delete.
     *
     * @var bool
     */
    protected $softDelete = true;

    /**
     * Validation rules.
     *
     * @var array
     */
    public static $rules = [
        'first_name' => 'required|alpha|min:2|max:20',
        'last_name' => 'required|alpha|min:2|max:20',
        'email' => 'required|email|unique:users',
        'password' => 'required_without:id|confirmed|min:8|max:50',
    ];

	/**
	 * Validation errors.
	 *
	 * @var array
	 */
	private $errors;

	/**
	 * Discount relation.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function discounts()
	{
		return $this->hasMany('Discount');
	}

	/**
	 * Rent relation.
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 */
	public function rents()
	{
		return $this->hasMany('Rent');
	}

	/**
	 * Full name.
	 *
	 * @return string
	 */
	public function name()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

	/**
	 * Returns validation errors.
	 *
	 * @return array
	 */
	public function getErrors()
    {
        return $this->errors;
    }

	/**
	 * Register user.
	 *
	 * @param array $data
	 *
	 * @return User User object
	 */
	public function register($data)
    {
        $v = Validator::make($data, self::$rules);

        if ($v->fails())
        {
            $this->errors = $v->errors();
            return false;
        }

        // Create the user
        $user = Sentry::createUser(array(
            'slug'       => $this->generateSlug($data),
            'first_name' => $data['first_name'],
            'last_name'  => $data['last_name'],
            'email'      => $data['email'],
            'password'   => $data['password'],
            'activated'  => false
        ));

        $usersGroup = Sentry::findGroupById(2);

        $user->addGroup($usersGroup);

        $user->sendActivationCode();

        return $user;
    }

	/**
	 * Generates unique slug for user.
	 *
	 * Bases on first and last name.
	 *
	 * @param $data
	 *
	 * @return string
	 */
	protected function generateSlug($data)
    {
        $i = 0;
        do
        {
            $slug = Str::slug($data['first_name'][0] . $data['last_name']);

            if($i > 0)
            {
                $slug .= '_' . $i;
            }

            ++$i;
        }
        while( $this->where('slug', '=', $slug)->count() != 0);

        return $slug;
    }

	/**
	 * Send email with activation code to user.
	 */
	public function sendActivationCode()
    {
        // to use in closure, cannot use lexical variable ($this)
        $user = $this->toArray();
        // activation_code is hidden in SentryUser model, so we add this manually
        $user['activation_code'] = $this->getActivationCode();
        $user['name'] = $this->name();

        Mail::later(5, 'users.emails.registration_confirm', $user, function($message) use ($user)
        {
            $message->to($user['email'], $user['name'])->subject('Potwierdź e-mail w serwisie Localeo');
        });

    }

	/**
	 * Send password reset code.
	 */
	public function sendResetPasswordCode()
    {
        // Generate new activation code
        $code = substr(md5(time() . uniqid()), 7, 34);
        $this->reset_password_code = $code;
        $this->save();

        // to use in closure, cannot use lexical variable ($this)
        $user = $this->toArray();
        // rese_code is hidden in SentryUser model, so we add this manually
        $user['reset_password_code'] = $code;
        $user['name'] = $this->name();

        Mail::later(5, 'users.emails.restore_password', $user, function($message) use ($user)
        {
            $message->to($user['email'], $user['name'])->subject('Odzyskaj hasło.');
        });

    }

	/**
	 * Mark user as deleted.
	 *
	 * @return bool
	 */
	public function delete()
    {
        $this->delete();
        return true;
    }

    /**
     * Get the token value for the "remember me" session.
     *
     * @return string
     */
    public function getRememberToken()
    {
        // TODO: Implement getRememberToken() method.
    }

    /**
     * Set the token value for the "remember me" session.
     *
     * @param  string $value
     * @return void
     */
    public function setRememberToken($value)
    {
        // TODO: Implement setRememberToken() method.
    }

    /**
     * Get the column name for the "remember me" token.
     *
     * @return string
     */
    public function getRememberTokenName()
    {
        // TODO: Implement getRememberTokenName() method.
    }
}

application/app/controllers/UsersController.php
<?php

class UsersController extends BaseController {

    /**
     * User Repository
     *
     * @var User
     */
    protected $user;

    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $users = $this->user->paginate($this->paginationLimit);

        return View::make('users.index', compact('users'));
    }

    public function getRegister()
    {
        return View::make('users.register');
    }

    public function postRegister()
    {
        $inputs = Input::all();

        $user = $this->user->register($inputs);
        if ( !$user )
        {
            $this->flashFailure('Sprawdź poprawność danych!');
            return Redirect::to('register')->withInput()->withErrors($this->user->getErrors());
        }

        Session::put('credentials', ['email' => $user->email, 'password' => $inputs['password']]);
        Auth::once(Session::get('credentials'));

		$user = Auth::user();
		$user->activated = 1;
		$user->save();

        return Redirect::route('accept_terms');
    }

    public function getTerms()
    {
        Auth::once(Session::get('credentials'));
        return View::make('users.terms');
    }

    public function postTerms()
    {
        Auth::once(Session::get('credentials'));

        if( ! Input::get('terms_accepted_at') )
        {
            return Redirect::route('accept_terms')->withInput()->withErrors([
                'terms_accepted_at' => 'Zaakceptuj regulamin.'
            ]);
        }

        $user = Auth::user();
        $user->terms_accepted_at = date('Y-m-d H:i:s');

        Auth::login(Auth::user());

        if($user->save())
        {
            $this->flashSuccess('Konto zostało utworzone. Potwierdź rejestrację klikając w link, który został wysłany na podany adres e-mail.');
            return Redirect::route('login');
        }

        $this->flashFailure('Błąd, spróbuj jeszcze raz!');
        return Redirect::route('accept_terms')->withInput()->withErrors([
            'terms_accepted_at' => 'Zaakceptuj regulamin.'
        ]);
    }

    public function activate($code)
    {

        $user = User::whereActivationCode($code)->first();

        // Attempt to activate the user
        if ($user && $user->attemptActivation($code))
        {
            $this->flashSuccess('Twoje konto jest aktywne. Witaj w Localeo!');
        }
        else
        {
            $this->flashFailure('Podany kod jest nieprawidłowy lub konto już zostało potwierdzone wcześniej. W razie problemów skontaktuj się z administratorem strony.');
        }

        if(Auth::check())
        {
            return Redirect::to('/');
        }

        return Redirect::route('login');
    }


    public function getLogin()
    {
        if(Auth::check())
        {
            $this->flashWarning(sprintf('Jesteś zalogowany.'));
            return Redirect::to('/');
        }

        return View::make('users.login');
    }

    public function postLogin()
    {

        $error = false;
        try
        {
            $user = Sentry::authenticate([
                'email'    => Input::get('email'),
                'password' => Input::get('password'),
            ]);

            Auth::attempt([
                'email'    => Input::get('email'),
                'password' => Input::get('password'),
            ]);
        }
        catch (Cartalyst\Sentry\Users\LoginRequiredException $e)
        {
            $error = 'Podaj login.';
        }
        catch (Cartalyst\Sentry\Users\PasswordRequiredException $e)
        {
            $error = 'Podaj hasło.';
        }
        catch (Cartalyst\Sentry\Users\WrongPasswordException $e)
        {
            $error = 'Złe hasło, spróbuj jeszcze raz.';
        }
        catch (Cartalyst\Sentry\Users\UserNotFoundException $e)
        {
            $error = 'Brak konta o podanym loginie.';
        }
        catch (Cartalyst\Sentry\Users\UserNotActivatedException $e)
        {
            $error = 'Konto nie zostało potwierdzone.';
        }
        catch (Cartalyst\Sentry\Throttling\UserSuspendedException $e)
        {
            $error = 'Konto zawieszone.';
        }
        catch (Cartalyst\Sentry\Throttling\UserBannedException $e)
        {
            $error = 'Konto zablokowane.';
        }

        if($error)
        {
            return View::make('users.login')->with('error', $error);
        }

        $this->flashSuccess(sprintf('Witaj %s. Miło Cię znowu widzieć!', $user->first_name));
        return Redirect::intended('/');
    }

    public function getLogout()
    {
        Auth::logout();
        $this->flashSuccess('Do zobaczenia wkrótce!');
        // Redirect to blog will be nice thing!
        return Redirect::route('/');
    }

    public function getRestorePasswordRequest()
    {
        return View::make('users.restore_password_request');
    }

    public function postRestorePasswordRequest()
    {
        try
        {
            // Find the user using the user email address
            $user = Sentry::findUserByLogin(Input::get('email'));

            $user->sendResetPasswordCode();

            $this->flashSuccess('Na adres e-mail zostały wysłany link do zmiany hasła. Postępuj zgodnie z instrukcjami.');
            return Redirect::route('/');
        }
        catch (Cartalyst\Sentry\Users\UserNotFoundException $e)
        {
            return View::make('users.restore_password_request')->with('error', 'Konto o podanym adresie e-mail nie istnieje.');
        }
    }


    public function getResetPassword($code)
    {
        return View::make('users.reset_password', ['resetPasswordCode' => $code]);
    }

    public function postResetPassword()
    {

        try
        {

            $user = Sentry::findUserByLogin(Input::get('email'));

            // Validates new password
            $v = Validator::make(Input::all(), ['password' => $this->user->rules['password']]);

            if($v->fails())
            {
                throw new Exception($v->errors()->get('password')[0]);
            }

            $invalidCode = 'Podany link do zmiany hasła jest nieprawidłowy. Spróbuj jeszcze raz kliknąć w link.';

            // Check if the reset password code is valid
            if ($user->checkResetPasswordCode(Input::get('password_reset_code')))
            {
                // Attempt to reset the user password
                if ($user->attemptResetPassword(Input::get('password_reset_code'), Input::get('password')))
                {
                    $this->flashSuccess('Hasło zostało zmienione.');
                    return Redirect::route('login');
                }
                else
                {
                    // Password reset failed
                    $this->flashFailure($invalidCode);
                }
            }
            else
            {
                $this->flashFailure($invalidCode);
            }

            return Redirect::to('/');
        }
        catch (Exception $e)
        {
            return View::make('users.reset_password', [
                'resetPasswordCode' => Input::get('password_reset_code'),
                'error' => $e->getMessage()
            ]);
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $user = $this->user->findOrFail($id);

        return View::make('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id = null)
    {
        if(!$id)
        {
            $user = Auth::user();
        }
        else
        {
            $user = $this->user->find($id);
        }

        if (is_null($user))
        {
            return Redirect::route('users.ro');
        }

        $userGroups = [];
        foreach($user->getGroups() as $g)
        {
            $userGroups[] = $g->id;
        }
        $groups = Group::lists('name', 'id');

        return View::make('users.edit', compact('user', 'groups', 'userGroups'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id = null)
    {
        if(!$id)
        {
            $id = Auth::user()->id;
        }
        $input = array_except(Input::all(), '_method');
        $rules = ['first_name' => User::$rules['first_name'], 'last_name' => User::$rules['last_name']];
        $validation = Validator::make($input, $rules);

        if ($validation->passes())
        {
            $newPass = Input::get('password');
            $sentryUser = Sentry::getUserProvider()->findById($id);
            if(!empty($newPass) )
            {
                $sentryUser->password = $newPass;

            }

            foreach(Sentry::findAllGroups() as $group)
            {
                $sentryUser->removeGroup($group);
            }

            foreach(Input::get('groups') as $groupId)
            {
                $g = Sentry::findGroupById($groupId);
                $sentryUser->addGroup($g);
            }
            $sentryUser->save();

            $user = $this->user->find($id);
            $user->update($input);

            return Redirect::route('users.show', $id);
        }

        return Redirect::route('users.edit', $id)
            ->withInput()
            ->withErrors($validation)
            ->with('message', 'Problem z walidacją.');
    }


    public function getSettings()
    {
        $user = Auth::user();
        return View::make('users.settings', compact('user'));
    }

    public function postSettings()
    {
        $id = Auth::user()->id;
        $input = array_except(Input::all(), '_method');

application/app/views/users/edit.blade.php
@extends('layouts.user', ['current' => 'users.index'])

<?php
$items = [
    'users.index' => 'Lista',
    ['users.edit', 'Edycja', [$user->id]],
    ['users.show', 'Podgląd', [$user->id]]
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'users.edit'])

@section('content2')

    {{ Former::open()->route('users.update', $user->id)->populate($user) }}

    {{ Former::text('first_name', 'Imię')->placeholder('Imię') }}
    {{ Former::text('last_name', 'Nazwisko')->placeholder('Nazwisko') }}

    {{ Former::select('groups[]', 'Grupa')->options($groups)->select($userGroups)->id('groups') }}
    {{ Former::password('password', 'Hasło')->placeholder('Pozostaw puste, aby nie zmieniać') }}

    {{ Former::actions()->large_primary_submit('Zapisz') }}

    {{ Former::close() }}

@stop

@include('packages.select')

application/app/views/users/index.blade.php
@extends('layouts.user', ['current' => 'users.index'])

<?php
$items = [
    'users.index' => 'Lista',
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'users.index'])

@section('content2')

    @if ($users->count())
        <div class="table-responsive">
            <table class="table table-blue">
                <thead>
                    <tr>
                        <th>Email</th>
                        <th>Imię</th>
                        <th>Nazwisko</th>
                        {{--<th>Aktywowany</th>--}}
                        <th>Grupy</th>
                        <th class="text-right">Menu</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <td>{{{ $user->email }}}</td>
                            <td>{{{ $user->first_name }}}</td>
                            <td>{{{ $user->last_name }}}</td>
                            {{--<td>{{ $user->activated ? 'Tak' : 'Nie' }}</td>--}}
                            <td>
                                @foreach($user->getGroups() as $group)
                                    {{ $group->name }}
                                @endforeach
                            </td>
                            <td class="text-right col-sm-2">
                            {{ link_to_route('users.show', 'Podląd', array($user->id), array('class' => 'btn btn-info')) }}
                            {{ link_to_route('users.edit', 'Edycja', array($user->id), array('class' => 'btn btn-warning')) }}
                            {{ link_to_route('discounts.edit', 'Przydziel zniżkę', array($user->id), array('class' => 'btn btn-warning')) }}
                    </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @include('partials.pagination', ['object' => $users])
    @else
        @nothingFound('Nie dodano żadnych users')
    @endif

@stop

application/app/views/users/login.blade.php
@extends('layouts.master')

@section('body_class') login @stop

{{-- Hide navbar --}}
@section('menu') @stop

@section('header-right-menu') @stop

@section('content-full-width')
    <div class="login-form-wrapper ">

        <div class="pt3em pb2em">

            <div class="container">
                <h1 class="text-center pb1em">Zaloguj się, aby kontynuować</h1>
                <div class="row form-outline-div">
                    <div class="col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2 well well-lg well-bd">

                        <div class="row">

                            <div class="col-sm-4 login-part">
                                <p class="lead">
                                    Masz już konto?
                                    @if(empty($error))
                                        <br class="visible-md visible-lg"/>
                                        <br class="visible-md visible-lg"/>
                                    @endif
                                </p>
                                @if( !empty($error))
                                    <p class="alert alert-danger">
                                        {{ $error }}
                                    </p>
                                @endif

                                {{ Former::open_vertical('login') }}
                                {{ Former::text('email')->label(null)->placeholder('E-mail') }}
                                {{ Former::password('password')->label(null)->placeholder('Hasło') }}
                                <p class="text-center">
                                    {{ Button::submit_info('Zaloguj się', ['class' => 'btn-large']) }}
                                </p>
                                <p class="text-center">
                                    {{ HTML::linkRoute('password_restore_request', 'Nie pamiętam hasła.') }}
                                </p>
                                {{ Former::close() }}
                            </div>
                            <div class="col-sm-8 register-part">
                                <p class="lead">Konto jest darmowe i pozbawione jakichkolwiek ukrytych opłat!</p>

                                <p class="pt2em text-center">
                                    {{ HTML::linkRoute('register', 'Utwórz konto', [], ['class' => 'btn btn-large btn-warning lead']) }}
                                </p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

@stop

application/app/views/users/register.blade.php
@extends('layouts.master')

{{-- Hide navbar --}}
@section('menu')
@stop

{{-- Hide right side of navbar --}}
@section('navbar-right-inner')
@stop

@section('content')

    <div class="row pt2em">
        <div class="col-sm-2">
            <p class="lead c-orange">Dobra robota!</p>
        </div>

        <div class="col-sm-10">
            To zajmie tylko chwilę, ale pozwoli Ci dotrzeć do wielu odbiorców!
        </div>
    </div>

    @include('partials.registration_steps', ['step' => 1])

@stop

@section('content-full-width')
    <hr class="large"/>
@stop

@section('content2')
    {{ Former::open() }}

  

    <p class="c-dark-brown lead">
        Szczegóły konta
    </p>

    <div class="row">
        <div class="col-sm-7 col-sm-offset-1">
            {{ Former::text('first_name')->label('Imię') }}
            {{ Former::text('last_name')->label('Nazwisko') }}
            {{ Former::text('email')->label('E-mail') }}
            {{ Former::password('password')->label('Hasło') }}
            {{ Former::password('password_confirmation')->label('Potwierdź hasło') }}
        </div>
    </div>

    <div class="clearfix"></div>

	{{ Former::actions( Button::submit_warning('Załóż konto')) }}


    {{ Former::close() }}

@stop

application/app/views/users/reset_password.blade.php
@extends('layouts.master')

@section('body_class') password-reset @stop

{{-- Hide navbar --}}
@section('menu') @stop

@section('header-right-menu') @stop

@section('content-full-width')
<div class="login-form-wrapper bg-clouds">

    <div class="pt3em pb2em">

        <div class="container">
            <h1 class="text-center pb1em">Nowe hasło</h1>
            <div class="row form-outline-div">
                <div class="col-sm-4 col-sm-offset-4 well well-lg well-bd pt3em">

                    <div  class="login-part">

                        @if( !empty($error))
                        <p class="alert alert-danger">
                            {{ $error }}
                        </p>
                        @endif

                        {{ Former::open_vertical('reset-password') }}
                        {{ Former::text('email')->label(null)->placeholder('Email')->required() }}
                        {{ Former::password('password')->label(null)->placeholder('Hasło')->required() }}
                        {{ Former::password('password_confirmation')->label(null)->placeholder('Potwierdź hasło')->required() }}
                        {{ Former::hidden('password_reset_code')->value($resetPasswordCode) }}
                        <p class="text-center">
                            {{ Button::submit_warning('Wyślij', ['class' => 'btn-large']) }}
                        </p>
                        {{ Former::close() }}
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

@stop

@section('header-css')
{{ HTML::style('css/pages/users/login.css') }}
@stop

@section('js-bottom')
{{ HTML::script('js/pages/users/login.js') }}
@stop

application/app/views/users/restore_password_request.blade.php
@extends('layouts.master')

@section('body_class') password-reset @stop

{{-- Hide navbar --}}
@section('menu') @stop

@section('header-right-menu') @stop

@section('content-full-width')
<div class="login-form-wrapper bg-clouds">

    <div class="pt3em pb2em">

        <div class="container">
            <h1 class="text-center pb1em">Nie pamiętasz hasła?</h1>
            <div class="row form-outline-div">
                <div class="col-sm-4 col-sm-offset-4 well well-lg well-bd pt3em">

                    <div  class="login-part">
                        <p class="pb2em">
                            Proszę wpisz swój e-mail, który podałeś podczas rejestracji.
                        </p>

                        @if( !empty($error))
                            <p class="alert alert-danger">
                                {{ $error }}
                            </p>
                        @endif

                        {{ Former::open_vertical() }}
                        {{ Former::text('email')->label(null)->placeholder('Email')->required() }}
                        <p class="text-center">
                            {{ Button::submit_warning('Wyślij wiadomość e-mail', ['class' => 'btn-large']) }}
                        </p>
                        <p class="text-center @if(empty($error)) pt3em @endif">
                            {{ HTML::linkRoute('login', 'Powrót do logowania') }}
                        </p>
                        {{ Former::close() }}
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

@stop

@section('header-css')
    {{ HTML::style('css/pages/users/login.css') }}
@stop

@section('js-bottom')
{{ HTML::script('js/pages/users/login.js') }}
@stop

application/app/views/users/settings.blade.php
@extends('layouts.user', ['current' => 'settings'])

@section('content')
    <h2>Ustawienia konta</h2>
@stop

@section('content2')

    {{ Former::open()->populate($user) }}

    {{ Former::text('first_name', 'Imię')->placeholder('Imię') }}
    {{ Former::text('last_name', 'Nazwisko')->placeholder('Nazwisko') }}
    {{ Former::password('password', 'Hasło')->placeholder('Pozostaw puste, aby nie zmieniać') }}
    {{ Former::actions()->large_primary_submit('Zapisz') }}

    {{ Former::close() }}

@stop

application/app/views/users/show.blade.php
@extends('layouts.user', ['current' => 'users.index'])

<?php
$items = [
    'users.index' => 'Lista',
    ['users.edit', 'Edycja', [$user->id]],
    ['users.show', 'Podgląd', [$user->id]],
];
?>
@include('partials.mid_menu_list', ['items' => $items, 'current' => 'users.show'])

@section('content2')

    <div class="table-responsive">
        <table class="table table-blue">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Imię</th>
                    <th>Nazwisko</th>
                    <th>Grupy</th>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>{{{ $user->email }}}</td>
					<td>{{{ $user->first_name }}}</td>
					<td>{{{ $user->last_name }}}</td>
                    <td>
                        @foreach($user->getGroups() as $group)
                        {{ $group->name }}
                        @endforeach
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    {{-- Form::open(array('class' => 'mt2em', 'method' => 'DELETE', 'route' => array('users.destroy', $user->id))) }}
    {{ Form::submit('Delete', array('class' => 'btn btn-danger remove-submit')) }}
    {{ Form::close() --}}
@stop

@include("packages.bootbox")